export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

export const USER_LOADING = 'USER_LOADING';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

export const GET_REMINDERS_SUCCESS = 'GET_REMINDERS_SUCCESS';
export const GET_REMINDERS_FAIL = 'GET_REMINDERS_FAIL';
export const VIEW_REMINDER_SUCCESS = 'VIEW_REMINDER_SUCCESS';
export const VIEW_REMINDER_FAIL = 'VIEW_REMINDER_FAIL';
export const ADD_REMINDER_SUCCESS = 'ADD_REMINDER_SUCCESS';
export const ADD_REMINDER_FAIL = 'ADD_REMINDER_FAIL';
export const DELETE_REMINDER_SUCCESS = 'DELETE_REMINDER_SUCCESS';
export const DELETE_REMINDER_FAIL = 'DELETE_REMINDER_FAIL';
export const UPDATE_REMINDER_SUCCESS = 'UPDATE_REMINDER_SUCCESS';
export const UPDATE_REMINDER_FAIL = 'UPDATE_REMINDER_FAIL';

export const GET_EVENTS_SUCCESS = 'GET_EVENTS_SUCCESS';
export const GET_EVENTS_FAIL = 'GET_EVENTS_FAIL';
export const VIEW_EVENT_SUCCESS = 'VIEW_EVENT_SUCCESS';
export const VIEW_EVENT_FAIL = 'VIEW_EVENT_FAIL';
export const ADD_EVENT_SUCCESS = 'ADD_EVENT_SUCCESS';
export const ADD_EVENT_FAIL = 'ADD_EVENT_FAIL';
export const DELETE_EVENT_SUCCESS = 'DELETE_EVENT_SUCCESS';
export const DELETE_EVENT_FAIL = 'DELETE_EVENT_FAIL';
export const UPDATE_EVENT_SUCCESS = 'UPDATE_EVENT_SUCCESS';
export const UPDATE_EVENT_FAIL = 'UPDATE_EVENT_FAIL';

export const GET_PRIORITIES_SUCCESS = 'GET_PRIORITIES_SUCCESS';
export const GET_PRIORITIES_FAIL = 'GET_PRIORITIES_FAIL';
export const VIEW_PRIORITY_SUCCESS = 'VIEW_PRIORITY_SUCCESS';
export const VIEW_PRIORITY_FAIL = 'VIEW_PRIORITY_FAIL';

export const SET_SCHEDULE_DATE_SUCCESS = 'SET_SCHEDULE_DATE_SUCCESS';
export const SET_SCHEDULE_DATE_FAIL = 'SET_SCHEDULE_DATE_FAIL';
export const VIEW_DAY_SCHEDULE_SUCCESS = 'VIEW_DAY_SCHEDULE_SUCCESS';
export const VIEW_DAY_SCHEDULE_FAIL = 'VIEW_DAY_SCHEDULE_FAIL';
export const VIEW_MONTH_SCHEDULE_SUCCESS = 'VIEW_MONTH_SCHEDULE_SUCCESS';
export const VIEW_MONTH_SCHEDULE_FAIL = 'VIEW_MONTH_SCHEDULE_FAIL';
